# -*- coding: utf-8 -*-
"""Data Table Display

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/data_table.ipynb
"""

import numpy as np
import pandas as pd
import IPython.display as display
import matplotlib
from matplotlib import pyplot as plt
import io
import base64

df = pd.read_excel('assaydata.xlsx')
selected_data = df.iloc[[3,14,25,36,47,58,69,80,91,102,113,124,135,146,157,168,179,190,201,212,223], [1,20,40,60,80,100,120]]
transposed_data = selected_data.T
time_points = [f"{i} min" for i in range(0, 140, 20)]
transposed_data.index = time_points

transposed_data.plot(figsize=(10, 6))
plt.xlabel('Time (in minutes)')
plt.ylabel('Value')
plt.title('Transposed Data Plot')
plt.grid(True)
plt.legend(title='Sample ID')
plt.show()

df.iloc[[3,14,25,36,47,58,69,80,91,102,113,124,135,146,157,168,179,190,201,212,223], [1,20,40,60,80,100,120]]

selected_data = df.iloc[[3,14,25,36,47,58,69,80,91,102,113,124,135,146,157,168,179,190,201,212,223], [1,20,40,60,80,100,120]]
transposed_data = selected_data.T
time_points = [f"{i} min" for i in range(0, 140, 20)]
transposed_data.index = time_points

selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

df_diff = selected_data.diff(axis=1)


print(df_diff)

selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

df_diff = selected_data.diff(axis=1)
df_diff = df_diff.fillna(0)

for column in df_diff.columns:
    plt.figure(figsize=(8, 5))
    plt.plot(df_diff.index, df_diff[column], marker='o', linestyle='-')
    plt.title(f'Plot of {column}')
    plt.xlabel('Index')
    plt.ylabel('Difference')
    plt.grid(True)
    plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('assaydata.xlsx')
selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

df_diff = selected_data.diff(axis=1)


df_diff = df_diff.fillna(0)

for column in df_diff.columns:
    plt.figure(figsize=(8, 5))
    plt.plot(df_diff.index, df_diff[column], marker='o', linestyle='-')
    plt.title(f'Plot of {column}')
    plt.xlabel('Δ Time')
    plt.ylabel('Time (minutes)')
    plt.grid(True)
    plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('assaydata.xlsx')

selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

difference = selected_data.iloc[:, -1] - selected_data.iloc[:, 0]
difference.name = 'Δ Time (0 minute and 120 minutes)'

result_table = selected_data.copy()
result_table['Δ Time (0 minute and 120 minutes)'] = difference

print(result_table)

plt.figure(figsize=(10, 6))


for column in selected_data.columns:
    plt.plot(selected_data.index, selected_data[column], marker='o', linestyle='-', label=f'Original {column}')


plt.plot(difference.index, difference, marker='o', linestyle='-', color='red', label='Δ Time (0 minute and 120 minutes)')


plt.xlabel('Time (minutes)')
plt.ylabel('Δ Time')
plt.title('Δ Time (0 minute and 120 minutes)')
plt.legend(loc='upper right')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('assaydata.xlsx')


selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

difference = selected_data.iloc[:, -1] - selected_data.iloc[:, 0]
difference.name = 'Δ Time (0 minute and 120 minutes)'

result_table = selected_data.copy()
result_table['Δ Time (0 minute and 120 minutes)'] = difference

print(result_table)


plt.figure(figsize=(10, 6))
for column in selected_data.columns:
    plt.plot(selected_data.index, selected_data[column], marker='o', linestyle='-', label=f'Original {column}')

plt.xlabel('Time (minutes)')
plt.ylabel('Enzyme activity (A 405)')
plt.title('Original Values')
plt.legend(loc='upper right')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(difference.index, difference, marker='o', linestyle='-', color='red', label='Δ Time (0 minute and 120 minutes)')
plt.xlabel('Time (minutes)')
plt.ylabel('Δ Time')
plt.title('Δ Time (0 minute and 120 minutes)')
plt.legend(loc='upper right')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('assaydata.xlsx')

selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

df_diff = selected_data.diff(axis=1)

df_diff = df_diff.fillna(0)

titles = [
    'Time 1 vs Time 20', 'Time 20 vs Time 40', 'Time 40 vs Time 60',
    'Time 60 vs Time 80', 'Time 80 vs Time 100', 'Time 100 vs Time 120'
]
colors = ['blue', 'green', 'red', 'purple', 'orange', 'brown']

for i, column in enumerate(df_diff.columns):
    plt.figure(figsize=(8, 5))
    plt.plot(df_diff.index, df_diff[column], marker='o', linestyle='-', color=colors[i])
    plt.title(titles[i])
    plt.xlabel('Δ Time')
    plt.ylabel('Time (minutes)')
    plt.grid(True)
    plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the data from the Excel file
df = pd.read_excel('assaydata.xlsx')

# Select specific rows and columns
selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

# Transpose the selected data
transposed_data = selected_data.transpose()

# Rename the x-axis
transposed_data.columns = [
    "0 minutes", "20 minutes", "40 minutes", "60 minutes", "80 minutes", "100 minutes", "120 minutes"
]

# Plot each row separately with customized titles and colors
for i, column in enumerate(transposed_data.columns):
    plt.figure(figsize=(8, 5))
    plt.plot(transposed_data.index, transposed_data[column], marker='o', linestyle='-')
    plt.title(f'Plot of {column}')
    plt.xlabel('Time')
    plt.ylabel('Values')
    plt.grid(True)
    plt.show()

# Print the transposed data to verify the changes
print(transposed_data)

import pandas as pd
import matplotlib.pyplot as plt

# Load the data from the Excel file
df = pd.read_excel('assaydata.xlsx')

# Select specific rows and columns
selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

# Rename the index (representing the columns) to the specified times
selected_data.columns = [
    "0 minutes", "20 minutes", "40 minutes", "60 minutes", "80 minutes", "100 minutes", "120 minutes"
]

# Transpose the selected data
transposed_data = selected_data.transpose()

# Plot each row separately with customized titles and colors
for i, column in enumerate(transposed_data.columns):
    plt.figure(figsize=(8, 5))
    plt.plot(transposed_data.index, transposed_data[column], marker='o', linestyle='-')
    plt.title(f'Plot of {column}')
    plt.xlabel('Time')
    plt.ylabel('Values')
    plt.grid(True)
    plt.show()

# Print the transposed data to verify the changes
print(transposed_data)



import pandas as pd
import matplotlib.pyplot as plt

# Load the data from the Excel file
df = pd.read_excel('assaydata.xlsx')

# Select specific rows and columns
selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

# Rename the index (representing the columns) to the specified times
selected_data.columns = [
    "0 minutes", "20 minutes", "40 minutes", "60 minutes", "80 minutes", "100 minutes", "120 minutes"
]

# Transpose the selected data
transposed_data = selected_data.transpose()

# Define the y-axis labels
y_labels = [
    "Sample - 1", "Sample - 2", "Sample - 3", "Sample - 4", "Sample - 5", "Sample - 6",
    "Sample - 1.a", "Sample - 2.a", "Sample - 3.a", "Sample - 4.a", "Sample - 5.a", "Sample - 6.a",
    "Positive control", "Negative control", "Background control",
    "NP - 0 nmol", "NP - 8 nmol", "NP - 16 nmol", "NP - 24 nmol", "NP - 32 nmol", "NP - 40 nmol"
]

# Plot each row separately with customized titles and colors
for i, column in enumerate(transposed_data.columns):
    plt.figure(figsize=(8, 5))
    plt.plot(transposed_data.index, transposed_data[column], marker='o', linestyle='-')
    plt.title(f'Plot of {column}')
    plt.xlabel('Time')
    plt.ylabel('Values')
    plt.yticks(transposed_data[column], y_labels)  # Set the y-axis labels
    plt.grid(True)
    plt.show()

# Print the transposed data to verify the changes
print(transposed_data)

import pandas as pd
import matplotlib.pyplot as plt

# Load the data from the Excel file
df = pd.read_excel('assaydata.xlsx')

# Select specific rows and columns
selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

# Rename the index (representing the columns) to the specified times
selected_data.columns = [
    "0 minutes", "20 minutes", "40 minutes", "60 minutes", "80 minutes", "100 minutes", "120 minutes"
]

# Transpose the selected data
transposed_data = selected_data.transpose()

# Define the y-axis labels
y_labels = [
    "Sample - 1", "Sample - 2", "Sample - 3", "Sample - 4", "Sample - 5", "Sample - 6",
    "Sample - 1.a", "Sample - 2.a", "Sample - 3.a", "Sample - 4.a", "Sample - 5.a", "Sample - 6.a",
    "Positive control", "Negative control", "Background control",
    "NP - 0 nmol", "NP - 8 nmol", "NP - 16 nmol", "NP - 24 nmol", "NP - 32 nmol", "NP - 40 nmol"
]

# Plot each row separately with customized titles and colors
for i, column in enumerate(transposed_data.columns):
    plt.figure(figsize=(8, 5))
    plt.plot(transposed_data.index, transposed_data[column], marker='o', linestyle='-')
    plt.title(f'Plot of {column}')
    plt.xlabel('Time')
    plt.ylabel('Values')
    plt.gca().set_yticklabels(y_labels)  # Set the y-axis labels
    plt.grid(True)
    plt.show()

# Print the transposed data to verify the changes
print(transposed_data)

import pandas as pd
import matplotlib.pyplot as plt

# Load the data from the Excel file
df = pd.read_excel('assaydata.xlsx')

# Select specific rows and columns
selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

# Rename the index (representing the columns) to the specified times
selected_data.columns = [
    "0 minutes", "20 minutes", "40 minutes", "60 minutes", "80 minutes", "100 minutes", "120 minutes"
]

# Transpose the selected data
transposed_data = selected_data.transpose()

# Define the y-axis labels
y_labels = [
    "Sample - 1", "Sample - 2", "Sample - 3", "Sample - 4", "Sample - 5", "Sample - 6",
    "Sample - 1.a", "Sample - 2.a", "Sample - 3.a", "Sample - 4.a", "Sample - 5.a", "Sample - 6.a",
    "Positive control", "Negative control", "Background control",
    "NP - 0 nmol", "NP - 8 nmol", "NP - 16 nmol", "NP - 24 nmol", "NP - 32 nmol", "NP - 40 nmol"
]

# Plot each row separately with customized titles and colors
for i, column in enumerate(transposed_data.columns):
    plt.figure(figsize=(8, 5))
    plt.plot(transposed_data.index, transposed_data[column], marker='o', linestyle='-')
    plt.title(y_labels[i])  # Use y-axis label as plot title
    plt.xlabel('Time')
    plt.ylabel('Values')
    plt.grid(True)
    plt.show()

# Print the transposed data to verify the changes
print(transposed_data)

import pandas as pd
import matplotlib.pyplot as plt

# Load the data from the Excel file
df = pd.read_excel('assaydata.xlsx')

# Select specific rows and columns
selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

# Rename the index (representing the columns) to the specified times
selected_data.columns = [
    "0 minutes", "20 minutes", "40 minutes", "60 minutes", "80 minutes", "100 minutes", "120 minutes"
]

# Transpose the selected data
transposed_data = selected_data.transpose()

# Define the y-axis labels
y_labels = [
    "Sample - 1", "Sample - 2", "Sample - 3", "Sample - 4", "Sample - 5", "Sample - 6",
    "Sample - 1.a", "Sample - 2.a", "Sample - 3.a", "Sample - 4.a", "Sample - 5.a", "Sample - 6.a",
    "Positive control", "Negative control", "Background control",
    "NP - 0 nmol", "NP - 8 nmol", "NP - 16 nmol", "NP - 24 nmol", "NP - 32 nmol", "NP - 40 nmol"
]

# Define colors for each plot
colors = ['blue', 'green', 'red', 'purple', 'orange', 'brown', 'cyan', 'magenta', 'yellow', 'black', 'gray', 'olive', 'lime', 'teal', 'maroon', 'navy', 'salmon', 'sienna', 'skyblue', 'tomato', 'violet']

# Plot each row separately with customized titles and colors
for i, column in enumerate(transposed_data.columns):
    plt.figure(figsize=(8, 5))
    plt.plot(transposed_data.index, transposed_data[column], marker='o', linestyle='-', color=colors[i])
    plt.title(y_labels[i])  # Use y-axis label as plot title
    plt.xlabel('Time')
    plt.ylabel('Values')
    plt.grid(True)
    plt.show()

# Print the transposed data to verify the changes
print(transposed_data)

import pandas as pd

# Load the data from the Excel file
df = pd.read_excel('assaydata.xlsx')

# Select specific rows and columns
selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

# Rename the index (representing the columns) to the specified times
selected_data.columns = [
    "0 minutes", "20 minutes", "40 minutes", "60 minutes", "80 minutes", "100 minutes", "120 minutes"
]

# Transpose the selected data
transposed_data = selected_data.transpose()

# Define the y-axis labels
y_labels = [
    "Sample - 1", "Sample - 2", "Sample - 3", "Sample - 4", "Sample - 5", "Sample - 6",
    "Sample - 1.a", "Sample - 2.a", "Sample - 3.a", "Sample - 4.a", "Sample - 5.a", "Sample - 6.a",
    "Positive control", "Negative control", "Background control",
    "NP - 8 nmol", "NP - 16 nmol", "NP - 24 nmol", "NP - 32 nmol", "NP - 40 nmol", "NP - 0 nmol"
]

# Print each transposed DataFrame separately
for i, column in enumerate(transposed_data.columns):
    print(f'Table for {y_labels[i]}:')
    print(transposed_data[[column]])
    print('\n')

pip install tabulate

import pandas as pd
from tabulate import tabulate

# Load the data from the Excel file
df = pd.read_excel('assaydata.xlsx')

# Select specific rows and columns
selected_data = df.iloc[
    [3, 14, 25, 36, 47, 58, 69, 80, 91, 102, 113, 124, 135, 146, 157, 168, 179, 190, 201, 212, 223],
    [1, 20, 40, 60, 80, 100, 120]
]

# Rename the index (representing the columns) to the specified times
selected_data.columns = [
    "0 minutes", "20 minutes", "40 minutes", "60 minutes", "80 minutes", "100 minutes", "120 minutes"
]

# Transpose the selected data
transposed_data = selected_data.transpose()

# Define the y-axis labels
y_labels = [
    "Sample - 1", "Sample - 2", "Sample - 3", "Sample - 4", "Sample - 5", "Sample - 6",
    "Sample - 1.a", "Sample - 2.a", "Sample - 3.a", "Sample - 4.a", "Sample - 5.a", "Sample - 6.a",
    "Positive control", "Negative control", "Background control",
    "NP - 0 nmol", "NP - 8 nmol", "NP - 16 nmol", "NP - 24 nmol", "NP - 32 nmol", "NP - 40 nmol"
]

# Print each transposed DataFrame separately
for i, column in enumerate(transposed_data.columns):
    print(f'Table for {y_labels[i]}:')
    print(tabulate(transposed_data[[column]], headers='keys', tablefmt='grid'))
    print('\n')